### ISSUE TITLE
Question : Encryption Keys

### ISSUE THREAD

**Issue by imattau** [adityakamble49/dcipher-app#4]
Hi, great work on the app. Quick question about the keys. 

I take it that the exported key is the public one that can be made available anywhere for other people to use to encrypt messages to be sent? 

This isn't clear in any of the documentation.

Clean and simple app. Well done.

**Comment by adityakamble49** [comment]
Your welcome. Glad you liked the app.

As of new it exports both the keys

Actually, I wanted to make use of same key to send and receive message. If the use case was like 1 sender and multiple receiver using 1 key I would have kept secret key private.


But as using 1 key user can share the key with someone and those two can share encrypted texts using single key.


As of now I haven't observed any adverse effect of that as long as only those 2 users keep the key to themselves.


Feel free to make any feature suggestion and bug report on GitHub

**Comment by adityakamble49** [comment]
Yes. It would, and in most of the application both keys kept separate. But for this application the use case is simple, and no need to share anything on website. 

But can be make better by creating two key pairs for 2 persons so we can keep the private key secret instead of sharing.
Still current way is also working, maybe this can be consider for security in future updates
